package com.momo.trung.enums;

public enum StateEnum {
    START,
    SELECTING_PRODUCT,
    DOING_DEPOSIT,
    CANCELLED,
    ASKING_CONFIRMATION,
    ASKING_DEPOSIT, ASKING_SELECTING_PRODUCT, NEXT_DAY, BOUGHT_PRODUCT, ASKING_NEXTDAY,
}
